openapi: 3.0.3
info:
  title: Clients orders API
  version: 1.0
  description: API for clients order
  termsOfService: http://some.terms.url
  contact:
    name: Ivan Ivanov
    email: example@mail.ru
    url: http://some.url
  license:
    name: GNU AGPLv3
    url: https://choosealicense.com/licenses/agpl-3.0/
servers:
  - url: http://localhost:8080
    description: local env
  - url: http://some.prod.url
    description: Production env
paths: {}